name: Hello World

on:
  push:
    branches:
      - 'task_#77'
    pull_requests:
      branches:
        - 'main'

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello World"
